"""
Django settings for ussdd project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import raven

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=4j$ub1-dhw!+e9@34kl0h0lzqsw_=3zul-yirernt*im$3cdr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ussd.test.servicesintegrity.com',"teksol.ngrok.io",'*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ussd.apps.UssdConfig',
    'raven.contrib.django.raven_compat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ussdd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ussdd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     },
#     'oracle': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': 'teksolprime',
#         'USER': 'C##TEKSOLPRIME',
#         'PASSWORD': 'ABCabc123',
#         'HOST': '192.168.1.125',
#         'PORT': '1521 ',
#     },
#     'sql': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'TEKSOL_MOBILE_DEMO',
#         'USER': 'teksol',
#         'PASSWORD': '=',
#         # 'HOST': '192.168.1.125',
#         'HOST': '172.17.203.6',
#         'PORT': '',
#     },
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     },
#     'oracle': {
#         'ENGINE': 'django.db.backends.oracle',
#         'NAME': 'teksolprime',
#         'USER': 'C##TEKSOLPRIME',
#         'PASSWORD': 'ABCabc123',
#         'HOST': '192.168.1.100',
#         # 'HOST': '197.251.253.48:90',
#         'PORT': '1521 ',
#     },
#     # 'oracle': {
#     #     'ENGINE': 'django.db.backends.oracle',
#     #     'NAME': 'teksolprime',
#     #     'USER': 'C##TEKSOLPRIME',
#     #     'PASSWORD': 'ABCabc123',
#     #     'HOST': '23.99.142.24',
#     #     # 'HOST': '192.168.1.100',
#     #     'PORT': '1521 ',
#     # },
#     'sql': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'PRIME5MOWEB',
#         'USER': 'pop',
#         'PASSWORD': 'pop',
#         # 'HOST': '197.251.253.48',
#         'HOST': '192.168.1.125',
#         'PORT': '',
#     },
#     # 'sql': {
#     #     'ENGINE': 'sql_server.pyodbc',
#     #     'NAME': 'PRIME5MOWEB',
#     #     'USER': 'teksol',
#     #     'PASSWORD': 'cumas5POP',
#     #     'HOST': 'teksolcloud.database.windows.net',
#     #     'PORT': '1433',
#     # },
# }
#

DATABASES = {
    'oracle': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'SISLDB',
        # 'USER': 'C##TEKSOLPRIME',
        'USER': 'SISLPRIME',
        # 'PASSWORD': 'ABCabc123',
        'PASSWORD': '11laborSUNDAY*$',
        # 'HOST': '192.168.1.125',
        'HOST': '172.17.202.8',
        'PORT': '1521 ',
    },
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },

    'sql': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'TEKSOL_MOBILE_DEMO',
        'USER': 'teksol',
        'PASSWORD': 'BubbleTop423',
        # 'HOST': '192.168.1.125',
        'HOST': '172.17.203.6',
        'PORT': '',
    },
    'danny': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'TEKSOL_MOBILE_DEMO',
        'USER': 'teksol',
        'PASSWORD': 'BubbleTop423',
        # 'HOST': '192.168.1.125',
        'HOST': '172.17.203.6',
        'PORT': '',
    },

}
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
# import os

RAVEN_CONFIG = {
    'dsn': 'https://d8bf61122f494810b2705deb312a80ae:c63520611b12435a88ff3817f2eff31a@sentry.io/1214034',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
}


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR,"django.log"),
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }
